#!/bin/sh

hwclock > /dev/null 2>&1
if [ $? -eq 0 ]; then
    hwclock $*
    exit $?
fi

file=/data/last-known-time

if [ "x$1" == "x-su" ]; then
    date -s @`cat $file`
elif [ "x$1" == "x-wu" ]; then
    date +%s > $file
fi

#now save the time to flash each minute
killall dummy-timekeeper
dummy-timekeeper < /dev/null > /dev/null 2>&1 &
