#!/bin/sh
module=brcmfmac

wpa_cli list_net | grep TEMP-DISABLED > /dev/null 2>&1 
if [ $? -eq 0 ]; then
    logger -t wifi Reloading $module
    rfkill unblock all
    rmmod $module
    modprobe $module
    wpa_cli flush > /dev/null 2>&1
    wpa_cli reconf > /dev/null 2>&1
fi

