#! /bin/sh

module=rtc-ds1307
address=0x68
driver=ds1307

case "$1" in
  start)
    modprobe $module
    echo $driver $address > /sys/class/i2c-adapter/i2c-1/new_device
    hwclock_wrapper -su
    ;;
  stop)
    hwclock_wrapper -wu
    ;;
  restart|reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0

