#!/bin/sh
#
# wlandev
#
# Make sure that the builtin wifi on the RPi is always wlan0
wlan0_wanted_prefix="b8:27:eb"

start() {
    if [ ! -f /sys/class/net/wlan0/address ]; then
        echo "No wlan0 device found"
        exit 1
    fi
    wlan0_prefix=`cat /sys/class/net/wlan0/address | cut -c1-8`
    if [ "$wlan0_prefix" != "$wlan0_wanted_prefix" ];  then
        for d in /sys/class/net/wlan*; do 
            this_device=`basename $d`
            prefix=`cat /sys/class/net/$this_device/address | cut -c1-8`
            if [ "$prefix" == "$wlan0_wanted_prefix" ]; then
                ip link set wlan0 down
                ip link set wlan0 name wlan0_old
                ip link set $this_device down
                ip link set $this_device name wlan0
                ip link set wlan0_old name $this_device
                ip link set wlan0 up
                ip link set $this_device up
                echo "swapped wlan0 and $this_device"
                exit 0
            fi
        done
        echo "Could not find RPi3 wlan0 device"
        exit 1
    fi
    echo "wlan0 device Ok"

}

case "$1" in
    start)
        start
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
