#! /bin/sh

NAME=ntpd
DAEMON=/usr/sbin/$NAME
NTP_SERVER=0.pool.ntp.org

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    /usr/bin/ntpdate -s $NTP_SERVER
    [ $? = 0 ] && hwclock -wu
    start-stop-daemon -S -q -x $DAEMON -- -g
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    echo -n "Current time: "
    date
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
