#!/bin/sh
#
# wifi
#
dev=wlan0
conf=/data/wpa_supplicant.conf
pid=/var/run/wpa_supplicant.pid

start() {
	wpa_supplicant -Dnl80211 -i$dev -c$conf -P$pid -B
	sleep 1
	ifup wlan0
        echo "OK"
}
stop() {
	kill `cat $pid`
	ifdown $dev
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
