#!/bin/sh

dev=/dev/mmcblk0p3
dir=/app

mount_fs() {
    mount $dev $dir
    if [ $? -ne 0 ]; then
        mkfs.ext4 -F $dev
        mount $dev $dir
        if [ $? -ne 0 ]; then
            echo "Failed to prepare $dev"
            exit 1
        fi
    fi
}

start() {
    mount_fs

}
stop() {
    umount $dir
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
  	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

