#!/bin/sh
#
# runsvdir
#
pid=/var/run/runsvdir.pid
service_dir=/app/service

start() {
    mkdir -p $service_dir
    /usr/bin/runsvdir $service_dir 2>&1 < /dev/null &
    echo $! > $pid
    echo "OK"
}

stop() {
    kill `cat $pid`
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
