#!/bin/sh
#
# hostapd
#
wlan_dev=wlan0
dev=uap0
conf=/data/hostapd.conf
pid=/var/run/hostapd.pid
ssid="Pi_`cat /sys/class/net/wlan0/address  | sed s/://g | cut -c1-12`"

start() {
    iw dev wlan0 interface add uap0 type __ap
    if [ ! -f $conf ]; then
        sed s/RENAME_ME/$ssid/g /etc/hostapd.conf > $conf
    fi
	hostapd -i$dev -P$pid -B $conf
    echo "OK"
}
stop() {
	kill `cat $pid`
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
