#!/bin/sh

led=/sys/class/leds/led1

start() {
	echo none > $led/trigger
	echo 0 > $led/brightness
}

stop() {
	echo input > $led/trigger
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

