#!/bin/sh
#
# monit
#
alt_conf=/app/etc/monitrc

start() {
    if [ -f $alt_conf ]; then
        monit -c $alt_conf
    else
        monit
    fi
    sleep 3
    monit start all
    monit monitor all
    echo "OK"
}
stop() {
    monit stop all
    monit unmonitor all
    echo "OK"
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
