#!/bin/sh
#
# watch_wifi
#

start() {
	mkdir -p /var/spool/cron/crontabs/
	crontab /etc/crontab
	crond
        echo "OK"
}
stop() {
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
